### ISSUE TITLE
Module not found: Error: Can't resolve 'vue' in '/dist/v3'

### ISSUE THREAD

**Issue by nimatrengo** [ChuHoMan/vue-demi-component-template#12]
Hello team 
After building the component, I am not able to install it anywhere, 
So the approach is to create components with Vue3 and build them for Vue2.7, so I need to install the component on Vue2.7 application, 
How this library could help me to achieve my goal? 

The way I am importing the build
```
import * as AppVueThree from 'vue-demi-template-component'
```
Error: 
```
Error: Can't resolve 'vue' in '/dist/v3'
```

**Comment by ChuHoMan** [comment]
Is there a reproduction link？You may need to **install Vue dependencies in your app using `vue-demi-template-component`**, as the user's version of Vue is determined，`vue-demi-template-component` can detect user vue version and use correct dist.

**Comment by nimatrengo** [comment]
I just fixed it by removing the globals and externals in the vite configuration and the component is working properly, would you recommend it?

**Comment by ChuHoMan** [comment]
It is definitely not recommended because you will have `Vue` in your application, as the library should not build dependencies, which will increase the size of the build files and there may be multiple Vue versions

**Comment by nimatrengo** [comment]
> Is there a reproduction link？You may need to **install Vue dependencies in your app using `vue-demi-template-component`**, as the user's version of Vue is determined，`vue-demi-template-component` can detect user vue version and use correct dist.

Can you give me an example please?

**Comment by ChuHoMan** [comment]
I don't have time at the moment, but you can look at how `VueUse` is used in projects, and that's the most common example.
