### ISSUE TITLE
build失败

### ISSUE THREAD

**Issue by wangjiudeng** [ChuHoMan/vue-demi-component-template#14]
node_modules/.pnpm/@vue+shared@3.2.36/node_modules/@vue/shared/dist/shared.d.ts:110:54 - error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

110 export declare const isSet: (val: unknown) => val is Set<any>;

**Comment by wangjiudeng** [comment]
Found 33 errors in 5 files.

Errors  Files
     5  node_modules/.pnpm/@vue+compiler-core@3.2.36/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:1043
    21  node_modules/.pnpm/@vue+reactivity@3.2.36/node_modules/@vue/reactivity/dist/reactivity.d.ts:55
     4  node_modules/.pnpm/@vue+run

**Comment by wangjiudeng** [comment]
假如当组件库使用的时候，需不需要build。是不是直接放git上，其他项目install是不是就可以了？

**Comment by ChuHoMan** [comment]
1. Have you run pnpm install beforehand? I haven't encountered any build failures on my end.
2. To make the component library usable, you need to publish it to npm.

----

1. 你预先执行了 `pnpm install` 了吗？我这边没遇到过 `build` 失败。
2. 如果要让组件库使用，需要 `publish` 到 `npm` 中

**Comment by wangjiudeng** [comment]
预先执行了

**Comment by ChuHoMan** [comment]
提供更多的信息，在命令行执行 `npx envinfo --system --binaries --browsers`。其次可以尝试删除 node_modules 重新进行 `pnpm install`
