### ISSUE TITLE
dist文件未正确工作

### ISSUE THREAD

**Issue by wtt19980923** [ChuHoMan/vue-demi-component-template#16]
我clone了当前项目的main分支,并进行了build,之后在html中使用dist文件,如下:

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
      <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
    <script src="./dist/v3/index.umd.js"></script>
  </head>
  <body>

    
    <div id="app">
        <vue-demi-template-component></vue-demi-template-component>
    </div>
  </body>
  <script>
      const app = Vue.createApp({})
      app.use(VueDemiTemplateComponent)
      app.mount('#app')
  </script>
</html>
<vue-demi-template-component></vue-demi-template-component> 这个标签未按照正常预期输出

**Comment by ChuHoMan** [comment]
请提供最小复现，你可能存在错误的操作。

**Comment by wtt19980923** [comment]
请问这个可以吗

**Comment by wtt19980923** [comment]
[test111.zip](https://github.com/ChuHoMan/vue-demi-component-template/files/13543278/test111.zip)
请问这个可以吗

**Comment by wtt19980923** [comment]
我试了一下,打包放到npm 通过npm下载的方式是可以支持到.但是通过cdn或者dist文件这个方式好像是用不了...

**Comment by ChuHoMan** [comment]
不好意思，我不方便打开 zip 压缩包。我猜测可能是路径问题，或者是打包时 global 设置的值没对应上

**Comment by wtt19980923** [comment]
![image](https://github.com/ChuHoMan/vue-demi-component-template/assets/59108577/ffe2787e-000d-4ffe-bd69-82dfa8ee9d27)
看起来不像是路径的问题,我打印 VueDemiTemplateComponent 是真实存在的

**Comment by ChuHoMan** [comment]
要看怎么访问 index.html 的，可能你需要启动一个静态服务器。

**Comment by wtt19980923** [comment]
我是通过vscode的liveserver和webstorm的内置服务器访问,结果都一样不行,放弃了 大佬
