### ISSUE TITLE
可以支持添加不同版本的图标库嘛，比如@ant-design/icons 或者iconify

### ISSUE THREAD

**Issue by baixjian** [ChuHoMan/vue-demi-component-template#17]

**Comment by ChuHoMan** [comment]
理论上是可以实现的，也不需要添加不同版本的图标库。有个前提，假设 icon 是 vue component，需要确保这个 vue component 是兼容 Vue3/2 的。一般这种情况最好根据 *.svg 批量生成 *.vue 的 icon 文件。

**Comment by baixjian** [comment]
> 理论上是可以实现的，也不需要添加不同版本的图标库。有个前提，假设 icon 是 vue component，需要确保这个 vue component 是兼容 Vue3/2 的。一般这种情况最好根据 *.svg 批量生成 *.vue 的 icon 文件。

已解决 使用unocss 的 icon 预设 感谢

**Comment by baixjian** [comment]
Found 34 errors in 5 files.

Errors  Files
     6  node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:63
    21  node_modules/.pnpm/@vue+reactivity@3.3.4/node_modules/@vue/reactivity/dist/reactivity.d.ts:64
     4  node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.d.ts:819
     1  node_modules/.pnpm/@vue+runtime-dom@3.3.4/node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:501
     2  node_modules/.pnpm/@vue+shared@3.3.4/node_modules/@vue/shared/dist/shared.d.ts:30
     
     项目拉一下来，直接build 会报错，请问是什么原因呀

**Comment by ChuHoMan** [comment]
没遇见过，可能的原因是切换 Vue 版本没成功？可以先尝试删除 node_modeuls 重新 pnpm i ，然后先执行一下pnpm run build:2 或者 pnpm run build:3 看看是否还有报错，如果有报错的话请发一下完整日志。

**Comment by baixjian** [comment]
项目直接拉下来，install后即可复现， 我也尝试下上面的步骤

**Comment by baixjian** [comment]
应该是pnpm type-check 的抛出异常
