### ISSUE TITLE
How to use vite-plugin-dts in a project

### ISSUE THREAD

**Issue by hjdbenny** [ChuHoMan/vue-demi-component-template#7]

**Comment by ChuHoMan** [comment]
I haven't practiced it before, and before I was going to manually expose the component *.d.ts directly  (because I didn't find that Vue2.6 has too good best practices), but vite-plugin-dts should work out of the box in Vue 2.7 and Vue3, you can try adding directly to the vite plugin option.

**Comment by hjdbenny** [comment]
![image](https://user-images.githubusercontent.com/28851909/236109563-ad5115c5-1eb8-41cf-92f9-a9625dbf1f94.png)
![image](https://user-images.githubusercontent.com/28851909/236109636-3644a8f4-21b2-409d-b839-be777fba34b6.png)
How to resolve?

**Comment by ChuHoMan** [comment]
`rootDir` problem. It seems that he thinks that the `src/index.ts` source code is not in the `playground` , maybe you can try adding `tsconfig.json` to the `playground` directory and include `src/**`, I should update this repository when I have time, or you can PR.

**Comment by ChuHoMan** [comment]
I have already resolved the issue, but the plugin does not support 2.6. For 2.6, you can choose to upgrade to 2.7 or manually write the .d.ts file.Thank you for bringing up the issue. I think I can close it now.
